# Generated by Django 4.1.7 on 2023-03-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Schema title')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Column_separator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Schema title')),
                ('symbol', models.CharField(max_length=1, verbose_name='Char for')),
            ],
        ),
        migrations.CreateModel(
            name='String_character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Schema title')),
                ('symbol', models.CharField(max_length=1, verbose_name='Char for')),
            ],
        ),
        migrations.CreateModel(
            name='TypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Rule title')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Schema title')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('column_separator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csv_main.column_separator')),
                ('columns', models.ManyToManyField(to='csv_main.column')),
                ('string_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csv_main.string_character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who created schema')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Rule title')),
                ('rule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csv_main.typerule')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_main.columntype'),
        ),
    ]
